### ISSUE TITLE
Is @agata on GitHub the same as the creator

### ISSUE THREAD

**Issue by machawk1** [ipfs/artwork#2]
In the `IPFS_Golden_Age_for_Libraries_illustrations/` directory in the root of the repo, the author is cited as @agata on GitHub. I believe this citation to be a mistake.

The avatar at https://github.com/agata does not appear to be the same person as the author at the linked site http://agata.krych.eu/. The GitHub user has no mention of graphic design where the author of the site and subsequent Twitter account ([@agata_krych](https://twitter.com/agata_krych)) seem to be the author.

I think the reference to the original author's GitHub should be removed/adjusted. I can submit a PR if I can obtain a confirmation of this mistake, potentially by @flyingzumwalt .

**Comment by flyingzumwalt** [comment]
Thank you for catching this! You're right. The creator is @akrych. I fixed it in the readme.
